# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4440cdbcb9714f3ad21052d39cfcee40adbbb969c67168eca86945dfc1d055caaf39304dc077e926b0bfa7d81bea23e854fae4324228759797851dc2fb066898

test:
  secret_key_base: 6175da22da6549346bf24575c370649c76982b705b4fe4809aab8acc3efe712d297c9939546da2f51558a1e8c6fc7fba45ee5e3f7a034f0bc8ccc076fcc0e86f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
